### PR TITLE
👽 Update Serverless `frameworkVersion` property

### PR DESCRIPTION
**Pull request by fboerncke**
added a hint to make sure that you have the right entry for the "frameworkVersion" property in the serverless.yaml file

### CODE REVIEW

**Comment by aswetlow** [comment]
Hey @fboerncke  
Thank you for the PR. I think it would also make sense to change the `frameworkVersion` in the boilerplate code to version 3. 
https://github.com/jovotech/jovo-cli/blob/v4/latest/integrations/target-serverless/src/index.ts#L25

What do you think?

**Comment by fboerncke** [comment]
I agree. I changed the setting in my generated file to "3" in my environment and it worked fine.

My only concern with this is that those users who update their  Jovo installation without updating their serverless installation wil run into the same problem when creating new projects that I had last week. The error message is not very helpful if the framework version numbers do not match.

Finally though I believe that using the latest version numbers as default makes sense, especially if you plan  to support the new AWS Function URL Lambdas in some future version of Jovo.

**Comment by aswetlow** [comment]
Awesome. Would you mind also updating the version?

**Comment by fboerncke** [comment]
OK, I'll do that soon ...

**Comment by fboerncke** [comment]
I added the modifications regarding V2 ==> V3 to the existing pull request.

**Review by aswetlow — APPROVED** [review]

**Comment by jankoenig** [comment]
Hi @fboerncke, thanks a lot for your updates! I wanted to make a few additional changes to the documentation. For that, could you please create a topic branch (e.g. `v4/serverless-version`, ideally based on the `v4/dev` branch) and push the updates to that one? 

Also, I switched the target branch from v4/latest to v4/dev. Learn more here: https://www.jovo.tech/docs/contributing#branches

Thank you!

**Comment by fboerncke** [comment]
Hi @jankoenig, currently I am on holiday and will return to the keyboard around next Wednesday. I can take care of your request then. But if it is somehow urgent then feel free to drop/refuse my PR and introduce my some changes into your branch to speed up the process. 
Bye, 
Frank

**Comment by jankoenig** [comment]
Thank you @fboerncke. I merged your changes into a new branch and created a new PR (#329) from it. This way, your changes stay connected to your account. Thanks for your help 🎉  enjoy your holidays

**Pull request closed without merging**
