### PR TITLE
Speeding up Travis build and switching from Node 7 to 8/10

### PR DESCRIPTION
**Pull request by IGx89**
## Proposed changes
Some small Travis CI build improvements. Got rid of unnecessary installs and switched to the faster `npm ci` (along with checking in the requisite package-lock.json), as well as switching the builds from running on Node.js 7 (EOL'd) to Node.js 8 (LTS) and 10 (Latest).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by IGx89** [comment]
The build is at least 30 seconds faster now :)

**Comment by aswetlow** [comment]
Make sense! Thank you 👍

**Comment by renatoalencar** [comment]
Removing version 7 of Node implies to not support it at all? Because, this way, you guys could use several resources of those new versions of Node, making the code very cleaner.

**Comment by IGx89** [comment]
No, just that tests aren’t being run on it anymore. They support down to Node.js v4 I believe

**Comment by renatoalencar** [comment]
I don't know, but support down to version 4 makes sense nowdays? Even the version 7, now that the LTS version is the 8.

**Comment by jankoenig** [comment]
Yes, this makes sense @renatoalencar. We won't support lower versions of node in Jovo `v2`

**Pull request merged**
