### PR TITLE
Addressed issue where vorpal actions weren't signaling done.

### PR DESCRIPTION
**Pull request by IGx89**
## Proposed changes
This resolves issue #62. I've also enhanced the unit tests to catch this issue as well, simplifying them a bit in the process.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by IGx89** [comment]
Unsure. Are you able to re-run the build and see if it still happens?

**Comment by IGx89** [comment]
I set up Travis on my own repo and added logging on stderr and found "listen EADDRINUSE :::3000" -- I had a suspicion it'd be something like that. Digging deeper, stay tuned...

**Comment by IGx89** [comment]
Fixed the issue! Was caused by a Linux-specific behavior that was preventing child processes (`node index.js`) of child processes (`jovo run`) from being terminated when the child process was terminated. I added a listener in `run.js` to ensure the child process is still terminated in that situation.

I also refactored the `testRun.js` tests a bit and removed an unnecessary test (--webhook-standalone isn't a valid parameter)

**Comment by aswetlow** [comment]
Great! Thank you so much!

**Comment by IGx89** [comment]
Thanks for merging! Any idea when the next release might be?

**Comment by aswetlow** [comment]
Just released. Thanks again!

**Pull request merged**
